//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Entidades
{
    public partial class AlumnosEntities : ObjectContext
    {
        public const string ConnectionString = "name=AlumnosEntities";
        public const string ContainerName = "AlumnosEntities";
    
        #region Constructors
    
        public AlumnosEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public AlumnosEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public AlumnosEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<SesionActual> SesActuales
        {
            get { return _sesActuales  ?? (_sesActuales = CreateObjectSet<SesionActual>("SesActuales")); }
        }
        private ObjectSet<SesionActual> _sesActuales;
    
        public ObjectSet<Sesion> Sesiones
        {
            get { return _sesiones  ?? (_sesiones = CreateObjectSet<Sesion>("Sesiones")); }
        }
        private ObjectSet<Sesion> _sesiones;
    
        public ObjectSet<Usuario> Usuarios
        {
            get { return _usuarios  ?? (_usuarios = CreateObjectSet<Usuario>("Usuarios")); }
        }
        private ObjectSet<Usuario> _usuarios;
    
        public ObjectSet<sActiva> sActivas
        {
            get { return _sActivas  ?? (_sActivas = CreateObjectSet<sActiva>("sActivas")); }
        }
        private ObjectSet<sActiva> _sActivas;

        #endregion

    }
}
