//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Entidades
{
    public partial class ContextoPantallas : ObjectContext
    {
        public const string ConnectionString = "name=ContextoPantallas";
        public const string ContainerName = "ContextoPantallas";
    
        #region Constructors
    
        public ContextoPantallas()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ContextoPantallas(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ContextoPantallas(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Curso> Cursos
        {
            get { return _cursos  ?? (_cursos = CreateObjectSet<Curso>("Cursos")); }
        }
        private ObjectSet<Curso> _cursos;
    
        public ObjectSet<Docente> Docentes
        {
            get { return _docentes  ?? (_docentes = CreateObjectSet<Docente>("Docentes")); }
        }
        private ObjectSet<Docente> _docentes;
    
        public ObjectSet<Grupo> Grupos
        {
            get { return _grupos  ?? (_grupos = CreateObjectSet<Grupo>("Grupos")); }
        }
        private ObjectSet<Grupo> _grupos;
    
        public ObjectSet<Horario> Horarios
        {
            get { return _horarios  ?? (_horarios = CreateObjectSet<Horario>("Horarios")); }
        }
        private ObjectSet<Horario> _horarios;
    
        public ObjectSet<Laboratorio> Laboratorios
        {
            get { return _laboratorios  ?? (_laboratorios = CreateObjectSet<Laboratorio>("Laboratorios")); }
        }
        private ObjectSet<Laboratorio> _laboratorios;
    
        public ObjectSet<Asignatura> Asignaturas
        {
            get { return _asignaturas  ?? (_asignaturas = CreateObjectSet<Asignatura>("Asignaturas")); }
        }
        private ObjectSet<Asignatura> _asignaturas;
    
        public ObjectSet<Carrera> Carreras
        {
            get { return _carreras  ?? (_carreras = CreateObjectSet<Carrera>("Carreras")); }
        }
        private ObjectSet<Carrera> _carreras;
    
        public ObjectSet<Aviso> Avisos
        {
            get { return _avisos  ?? (_avisos = CreateObjectSet<Aviso>("Avisos")); }
        }
        private ObjectSet<Aviso> _avisos;

        #endregion

    }
}
