//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Entidades
{
    public partial class Curso
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string MesInicio
        {
            get;
            set;
        }
    
        public virtual string MesFin
        {
            get;
            set;
        }
    
        public virtual int Año
        {
            get;
            set;
        }
    
        public virtual int Fase
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<Grupo> Grupo
        {
            get
            {
                if (_grupo == null)
                {
                    var newCollection = new FixupCollection<Grupo>();
                    newCollection.CollectionChanged += FixupGrupo;
                    _grupo = newCollection;
                }
                return _grupo;
            }
            set
            {
                if (!ReferenceEquals(_grupo, value))
                {
                    var previousValue = _grupo as FixupCollection<Grupo>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupGrupo;
                    }
                    _grupo = value;
                    var newValue = value as FixupCollection<Grupo>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupGrupo;
                    }
                }
            }
        }
        private ICollection<Grupo> _grupo;
    
        public virtual ICollection<Asignatura> Asignatura
        {
            get
            {
                if (_asignatura == null)
                {
                    var newCollection = new FixupCollection<Asignatura>();
                    newCollection.CollectionChanged += FixupAsignatura;
                    _asignatura = newCollection;
                }
                return _asignatura;
            }
            set
            {
                if (!ReferenceEquals(_asignatura, value))
                {
                    var previousValue = _asignatura as FixupCollection<Asignatura>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupAsignatura;
                    }
                    _asignatura = value;
                    var newValue = value as FixupCollection<Asignatura>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupAsignatura;
                    }
                }
            }
        }
        private ICollection<Asignatura> _asignatura;

        #endregion

        #region Association Fixup
    
        private void FixupGrupo(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Grupo item in e.NewItems)
                {
                    item.Curso = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Grupo item in e.OldItems)
                {
                    if (ReferenceEquals(item.Curso, this))
                    {
                        item.Curso = null;
                    }
                }
            }
        }
    
        private void FixupAsignatura(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Asignatura item in e.NewItems)
                {
                    item.Curso = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Asignatura item in e.OldItems)
                {
                    if (ReferenceEquals(item.Curso, this))
                    {
                        item.Curso = null;
                    }
                }
            }
        }

        #endregion

    }
}
