//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Entidades
{
    public partial class Docente
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Nombre
        {
            get;
            set;
        }
    
        public virtual string Descripcion
        {
            get;
            set;
        }
    
        public virtual byte[] Foto
        {
            get;
            set;
        }
    
        public virtual string RutaImg
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<Horario> Horario
        {
            get
            {
                if (_horario == null)
                {
                    var newCollection = new FixupCollection<Horario>();
                    newCollection.CollectionChanged += FixupHorario;
                    _horario = newCollection;
                }
                return _horario;
            }
            set
            {
                if (!ReferenceEquals(_horario, value))
                {
                    var previousValue = _horario as FixupCollection<Horario>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupHorario;
                    }
                    _horario = value;
                    var newValue = value as FixupCollection<Horario>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupHorario;
                    }
                }
            }
        }
        private ICollection<Horario> _horario;

        #endregion

        #region Association Fixup
    
        private void FixupHorario(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Horario item in e.NewItems)
                {
                    item.Docente = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Horario item in e.OldItems)
                {
                    if (ReferenceEquals(item.Docente, this))
                    {
                        item.Docente = null;
                    }
                }
            }
        }

        #endregion

    }
}
