//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Entidades
{
    public partial class SesionActual
    {
        #region Primitive Properties
    
        public virtual int AS_ID
        {
            get;
            set;
        }
    
        public virtual int AS_SE_ID
        {
            get { return _aS_SE_ID; }
            set
            {
                if (_aS_SE_ID != value)
                {
                    if (Sesion != null && Sesion.SE_ID != value)
                    {
                        Sesion = null;
                    }
                    _aS_SE_ID = value;
                }
            }
        }
        private int _aS_SE_ID;
    
        public virtual bool AS_INICIADA
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> AS_REPORTE
        {
            get;
            set;
        }
    
        public virtual string AS_US_DESCR
        {
            get { return _aS_US_DESCR; }
            set
            {
                if (_aS_US_DESCR != value)
                {
                    if (Usuario != null && Usuario.US_NOMBRE != value)
                    {
                        Usuario = null;
                    }
                    _aS_US_DESCR = value;
                }
            }
        }
        private string _aS_US_DESCR;

        #endregion

        #region Navigation Properties
    
        public virtual Sesion Sesion
        {
            get { return _sesion; }
            set
            {
                if (!ReferenceEquals(_sesion, value))
                {
                    var previousValue = _sesion;
                    _sesion = value;
                    FixupSesion(previousValue);
                }
            }
        }
        private Sesion _sesion;
    
        public virtual Usuario Usuario
        {
            get { return _usuario; }
            set
            {
                if (!ReferenceEquals(_usuario, value))
                {
                    var previousValue = _usuario;
                    _usuario = value;
                    FixupUsuario(previousValue);
                }
            }
        }
        private Usuario _usuario;

        #endregion

        #region Association Fixup
    
        private void FixupSesion(Sesion previousValue)
        {
            if (previousValue != null && previousValue.SesionActual.Contains(this))
            {
                previousValue.SesionActual.Remove(this);
            }
    
            if (Sesion != null)
            {
                if (!Sesion.SesionActual.Contains(this))
                {
                    Sesion.SesionActual.Add(this);
                }
                if (AS_SE_ID != Sesion.SE_ID)
                {
                    AS_SE_ID = Sesion.SE_ID;
                }
            }
        }
    
        private void FixupUsuario(Usuario previousValue)
        {
            if (previousValue != null && previousValue.SesionActual.Contains(this))
            {
                previousValue.SesionActual.Remove(this);
            }
    
            if (Usuario != null)
            {
                if (!Usuario.SesionActual.Contains(this))
                {
                    Usuario.SesionActual.Add(this);
                }
                if (AS_US_DESCR != Usuario.US_NOMBRE)
                {
                    AS_US_DESCR = Usuario.US_NOMBRE;
                }
            }
        }

        #endregion

    }
}
