//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Entidades
{
    public partial class Sesion
    {
        #region Primitive Properties
    
        public virtual int SE_ID
        {
            get;
            set;
        }
    
        public virtual int SE_NUM_EQP
        {
            get;
            set;
        }
    
        public virtual int SE_NUM_LAB
        {
            get;
            set;
        }
    
        public virtual string SE_US_DESCR
        {
            get;
            set;
        }
    
        public virtual System.DateTime SE_INICIO
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> SE_TERMINO
        {
            get;
            set;
        }
    
        public virtual string SE_CIERRE
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<SesionActual> SesionActual
        {
            get
            {
                if (_sesionActual == null)
                {
                    var newCollection = new FixupCollection<SesionActual>();
                    newCollection.CollectionChanged += FixupSesionActual;
                    _sesionActual = newCollection;
                }
                return _sesionActual;
            }
            set
            {
                if (!ReferenceEquals(_sesionActual, value))
                {
                    var previousValue = _sesionActual as FixupCollection<SesionActual>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSesionActual;
                    }
                    _sesionActual = value;
                    var newValue = value as FixupCollection<SesionActual>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSesionActual;
                    }
                }
            }
        }
        private ICollection<SesionActual> _sesionActual;

        #endregion

        #region Association Fixup
    
        private void FixupSesionActual(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SesionActual item in e.NewItems)
                {
                    item.Sesion = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SesionActual item in e.OldItems)
                {
                    if (ReferenceEquals(item.Sesion, this))
                    {
                        item.Sesion = null;
                    }
                }
            }
        }

        #endregion

    }
}
